export const skills = {
  html: require("@/assets/images/skills/html.png"),
  css: require("@/assets/images/skills/css.png"),
  js: require("@/assets/images/skills/javascript.png"),
  ts: require("@/assets/images/skills/typescript.png"),
  react: require("@/assets/images/skills/react.png"),
  next: require("@/assets/images/skills/nextjs.png"),
  materialUi: require("@/assets/images/skills/material-ui.png"),
  tailwind: require("@/assets/images/skills/tailwind-css.png"),
  git: require("@/assets/images/skills/git.png"),
  swiper: require("@/assets/images/skills/swiper.svg"),
  shadcnUi: require("@/assets/images/skills/shadcnui.png"),
  sass: require("@/assets/images/skills/sass.png"),
  reactQuery: require("@/assets/images/skills/reactquery.png"),
  redux: require("@/assets/images/skills/redux.png"),
  framer: require("@/assets/images/skills/framer-motion.svg"),
  styledComponents: require("@/assets/images/skills/file-type-styled.svg"),
  chartJs: require("@/assets/images/skills/chartjs.svg"),
  zustand: require("@/assets/images/skills/zustand.png"),
  axios: require("@/assets/images/skills/axios.webp"),
};
