export const SKILLS = {
  frontend: [
    "Html",
    "Css",
    "JavaScript",
    "TypeScript",
    "React Js",
    "Next Js",
    "Material Ui",
    "Tailwind Css",
    "Shadcn/ui",
    "Headless Ui",
    "Redux(Toolkit)",
    "Zustand",
    "React Query",
    "Swiper",
    "Chart Js",
    "Axios",
    "Framer Motion",
    "Git & Github",
  ],
  backend: [],
};
